version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: vite_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # <-- ¡Esta línea es clave!
    command: ["npm", "run", "dev", "--", "--host"]